getditto/DittoSwiftTools

Sources/DittoDataBrowser/DataBrowser.swift
Sources/DittoDataBrowser/DataBrowserViewModel.swift
Sources/DittoDataBrowser/Documents.swift
Sources/DittoDataBrowser/DocumentsViewModel.swift

Only starts a subscription if it's a standalone app (manually start them)

Data browser subscriptions

---

.swiftpm/xcode/xcshareddata/xcschemes/DittoDiskUsage.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/DittoPeersList.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/DittoPresenceViewer.xcscheme
DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/DittoManager.swift
DittoToolsApp/DittoToolsApp/Pages/ContentView.swift
DittoToolsApp/DittoToolsApp/Pages/DataBrowser.swift
DittoToolsApp/DittoToolsApp/Pages/PeersListViewer.swift
Package.swift
Sources/DittoPeersList/PeersListView.swift
Sources/DittoPeersList/PeersObserverVM.swift

New peers list updated with a more detailed view for iOS 15+

New peers list updated with a more detailed view for iOS 15+

---

Package.resolved
Sources/DittoPeersList/PeersListView.swift

Fix build error for PeersObserverVM 'localPeer'

---

.swiftpm/xcode/xcshareddata/xcschemes/DittoExportData.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/DittoExportLogs.xcscheme
DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/AppSettings.swift
DittoToolsApp/DittoToolsApp/DittoManager.swift
DittoToolsApp/DittoToolsApp/Pages/ContentView.swift
DittoToolsApp/DittoToolsApp/Pages/LoggingDetailsViewer.swift
Sources/DittoExportLogs/DittoLogger+LoggingOptions.swift
Sources/DittoExportLogs/LoggingDetailsView.swift

- move log level user feature to new LoggingDetailsView, bundling log level setting and  
logs exports features in a dedicated UI
- activate changes in logging for user selections in real time, without restarting Ditto  
- fix access to new Logging UI and feature from package

Refactor log level feature

---

DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/Pages/ContentView.swift
DittoToolsApp/DittoToolsApp/Pages/PermissionsHealthViewer.swift
Package.swift
README.md
Sources/DittoPermissionsHealth/NetworkManager.swift
Sources/DittoPermissionsHealth/PermissionsHealth.swift

Permissions Health tool

---

Sources/DittoHeartbeat/HeartbeatVM.swift

This will allow the user to check if the heartbeat is active from outside the module

Update access level of isEnabled

---

Sources/DittoHeartbeat/HeartbeatStrings.swift

update collection name

---

Sources/DittoHeartbeat/HeartbeatVM.swift

Don't subscribe to the heartbeat collection if not publishing heartbeat to the collection

---

Sources/DittoDiskUsage/Constants.swift
Sources/DittoDiskUsage/DiskUsageViewModel.swift

Default DiskUsage HealthMetric unhealthy limit to 500MB instead of 2GB

---

DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
Package.swift
Sources/DittoAllToolsMenu/AllToolsMenu.swift
Sources/DittoAllToolsMenu/DittoManager.swift
Sources/DittoAllToolsMenu/MenuListItem.swift
Sources/DittoAllToolsMenu/Pages/DataBrowser.swift
Sources/DittoAllToolsMenu/Pages/DiskUsageViewer.swift
Sources/DittoAllToolsMenu/Pages/HeartBeatViewer.swift
Sources/DittoAllToolsMenu/Pages/LoggingDetailsViewer.swift
Sources/DittoAllToolsMenu/Pages/PeersListViewer.swift
Sources/DittoAllToolsMenu/Pages/PermissionsHealthViewer.swift
Sources/DittoAllToolsMenu/Pages/PresenceDegradationViewer.swift
Sources/DittoAllToolsMenu/Pages/PresenceViewer.swift

New single point of entry for all tools

---

DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/Pages/AllToolsViewer.swift
DittoToolsApp/DittoToolsApp/Pages/ContentView.swift

Use SingleEntryPoint tool as the main view into all of the tools

---

Sources/DittoPeersList/PeersListView.swift
Sources/DittoPeersList/PeersObserverVM.swift

Replace remaining peerKey references with peerKeyString

---

Package.swift
README.md
Sources/DittoDiskUsage/DittoDiskUsageView.swift

Add ability to export data from DiskUsage

---

Sources/DittoPresenceViewer/DittoPresenceView.swift
Sources/DittoPresenceViewer/DittoPresenceViewController.swift

Adds Mac Catalyst support
Closes https://github.com/getditto/DittoSwiftTools/issues/135

Added Mac Catalyst Support

---

DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/DittoToolsApp.entitlements
Package.swift

It looks like we accidentally lost Mac Catalyst support somewhere, this adds it back

Adds Mac Catalyst support

---

Sources/DittoDiskUsage/DiskUsageViewModel.swift
Sources/DittoDiskUsage/DittoDiskUsageView.swift

Minor refactoring (and a few design/style updates, sorry) in Ditto instance retain management.

Fix Ditto instance retain cycle in DiskUsage module

---

DittoToolsApp/DittoToolsApp.xcodeproj/project.pbxproj
DittoToolsApp/DittoToolsApp/Views/ContentView.swift
DittoToolsApp/DittoToolsApp/Views/Credentials View/Components/FormField.swift
DittoToolsApp/DittoToolsApp/Views/Credentials View/CredentialsView.swift
DittoToolsApp/DittoToolsApp/Views/Credentials View/Form/FormView.swift
DittoToolsApp/DittoToolsApp/Views/Menu View/MenuView.swift
DittoToolsApp/DittoToolsApp/Views/UIScrollView+Extension.swift
Package.swift
Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/AllToolsMenu.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/DataBrowser.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/HeartBeatViewer.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/LoggingDetailsViewer.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PeersListViewer.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PermissionsHealthViewer.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PresenceDegradationViewer.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PresenceViewer.swift
Sources/DittoDataBrowser/DataBrowser.swift
Sources/DittoDataBrowser/Documents.swift
Sources/DittoDiskUsage/DittoDiskUsageView.swift
Sources/DittoExportData/ExportData.swift
Sources/DittoExportLogs/DittoLogManager.swift
Sources/DittoExportLogs/ExportLogs.swift
Sources/DittoExportLogs/Views/LoggingDetailsView.swift
Sources/DittoHeartbeat/HeartbeatView.swift
Sources/DittoPeersList/PeersListView.swift
Sources/DittoPermissionsHealth/PermissionsHealth.swift
Sources/DittoPresenceDegradation/NewSessionView.swift
Sources/DittoPresenceDegradation/PresenceDegradationView.swift

This allows the Tools App to build, but there the tools themselves need to be updated to support macOS. 
We will also want to revisit the Credentials screen UI as the labels need adjusting
This will at least allow us to start working on support for macOS for the individual tools

Add support for macOS

---

DittoToolsApp/DittoToolsApp/Views/Credentials View/CredentialsView.swift
Package.swift
Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/AllToolsMenu.swift
Sources/DittoDiskUsage/DittoDiskUsageView.swift
Sources/DittoExportData/ExportData.swift

fixes [CXTOOLs-423](https://linear.app/ditto/issue/CXTOOLS-423/macos-support-for-disk-usage)

Add support for macOS to DiskUsage and ExportData tools

---

Package.swift
Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PresenceViewer.swift

Closes CXTOOLS-426
Depends on https://github.com/getditto/DittoPresenceViewerCore/pull/10

Support macOS in the presence viewer tool

---

Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PermissionsHealthViewer.swift
Sources/DittoPermissionsHealth/PermissionsHealth.swift

fixes [CXTOOLS-425](https://linear.app/ditto/issue/CXTOOLS-425/macos-support-for-the-permissions-health-tool)

macOS support for permissionsHealth

---

Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/Tool Container Views/PeersListViewer.swift
Sources/DittoPeersList/PeersListView.swift

Update the Peers List tool to support macOS

---

Sources/DittoAllToolsMenu/MenuOption.swift
Sources/DittoAllToolsMenu/Views/AllToolsMenu.swift
Sources/DittoPeersList/PeersObserverVM.swift

Tweak a few things to fix Xcode warnings

Clean up Xcode warnings

---

README.md

Add the AllToolsMenu to the README

---

README.md

Clarify SwiftUI and UIKit implementation in All Tools Menu Section
